language: sh
install:
  - curl https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest -o /tmp/clitest -v
  - sed -i'' '2s/^/set -x /' /tmp/clitest
  - chmod +x /tmp/clitest

script: ./.travis-test.sh